### ISSUE TITLE
Email Setting Question

### ISSUE THREAD

**Issue by nccheckcashing** [periface/AbpCinotamZero-SmartAdmin#91]
Hello, 

First, thank you for sharing your code. 

Somehow, I got an error when I sent the email confirmation email. 

The exception is happen the below method in CinotamMailSenderDefault:
`
        async Task<bool> SendViaSmtp(MailMessage message)
        {
            try
            {
                var useSmtp = bool.Parse((await SettingManager.GetSettingValueAsync("UseSmtp")));

                if (!useSmtp) return false;
                await _emailSender.SendAsync(message);
                return true;
            }
            catch (Exception e)
            {
                Debug.WriteLine("Exception :" + e.Message);
                return false;
            }
        }
`

and the exception message is

**Exception :The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at**

I checked the SSL in the admin mail setting page like below. My email address and password are correct. 

SMTP host: smtp.gmail.com
SMTP port: 587
username:  my gmail address
password: my gmail password
domain name: gmail.com
Use SSL: checked
User default credentials: checked

Do you know what makes the exception?

**Comment by periface** [comment]
Hello, i think the problem is in the email service provider itself (gmail), anyway let me check it with my own credentials.

Question? is your visual studio instance configured for SSL.

**Comment by nccheckcashing** [comment]
Good morning, 

I did not configure the SSL for web in the visual studio. Only I checked "Use SSL" option in the admin email setting . 

When you test your credentials with Gmail, you may turn on the less secure app access option in your gmail account. If not, it will not allow to access the SMTP from you web app. 

Thanks.

**Comment by periface** [comment]
Ok, so its working now?

**Comment by nccheckcashing** [comment]
No, I explained how I setup the admin email setting and gmail. I'm waiting your testing result using your gmail account. Is your one is working? If it is working, could you share your admin email setting? I'm don't know what is the purpose of "domain name" in the admin email setting. Thanks.

**Comment by periface** [comment]
oooh ok, i will check it, but in my office the smpt ports are blocked, i´ll have to test it at my home.  And to be honest i haven´t properly tested the smpt option since i prefer to use http services (like sendgrid) to deliver emails :pensive: 
**This is my current config**
![image](https://cloud.githubusercontent.com/assets/8449812/23031263/f617bc46-f435-11e6-988a-cedee2713e6e.png)

You can check this issue too is on the framework source code repo

https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1143

Thanks to you. 

Pd. Sorry for my english.

**Comment by nccheckcashing** [comment]
Thank you for the reply.  Please test it at home. I will also check the framework source code repo too.

**Comment by periface** [comment]
I tested it yesterday and i had the same problem, i did some research and it looks like i'll have to work on a custom solution for this since this is a gmail-specific problem, Thanks for pointing this out :+1: .

**Comment by nccheckcashing** [comment]
Good morning, 

I found the solution from this blog [(link)](http://www.cnblogs.com/Wddpct/p/5919507.html). Domain name should be empty to send an email via gmail. 

But, It show me the following "InvalidOperationException" after sending the mail. 

> MailSenderAbpModule

> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.InvalidOperationException: MailSenderAbpModule
> 
> Source Error: 
> 
> 
> Line 33:             }
> Line 34:             ReleaseAll(providers);
> Line 35:             throw new InvalidOperationException(nameof(MailSenderAbpModule));
> Line 36: 
> Line 37:         }
> 
> Source File: C:\Users\...\AbpCinotamZero-SPA-only-master\AbpCinotamZero-SPA-only-master\Cinotam.ModuleZero.MailSender\CinotamMailSender\CinotamMailSender.cs    Line: 35 
> 

Do you have any idea?

**Comment by periface** [comment]
Yeah, my bad that code should be like this

![image](https://cloud.githubusercontent.com/assets/8449812/23073329/b1e7f73c-f4fa-11e6-93d0-d0d7ad9c955c.png)

The main idea is that the mail sender will throw an exception if none of the providers manage to deliver the mail message successfully (MailSent variable is the flag for it).

**Comment by periface** [comment]
Btw! in the **CinotamMailSenderDefault** the MailSent flag is never updated at all
![image](https://cloud.githubusercontent.com/assets/8449812/23073800/41a138ba-f4fc-11e6-800b-dd1de93f908a.png)

**The code should be like this.**
![image](https://cloud.githubusercontent.com/assets/8449812/23073724/0f5e9442-f4fc-11e6-9679-e3148c147f03.png)

That's why the code throws the error even if you manage to send the message via gmail.

**Comment by nccheckcashing** [comment]
Great! Thank you for the prompt response! It works now. Thank you so much.
